name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: kennethreitz/pipenv:latest

    steps:
      - uses: actions/checkout@master

      - name: Run tests
        run: |
          pipenv install --dev
          pipenv run pytest

  build:
    name: Build
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Build Dist
        run: |
          pip install setuptools wheel
          make build-pypi

      - name: Save dist
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist/

  publish:
    name: Publish
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v1
        with:
          python-version: '3.7.x'
          architecture: 'x64'

      - name: Get dist
        if: github.ref == 'refs/heads/master'
        uses: actions/download-artifact@v1
        with:
          name: dist

      - name: Publish
        if: github.ref == 'refs/heads/master'
        run: |
          pip install twine
          twine upload dist/* --username '${{ secrets.TWINE_USERNAME }}' --password '${{ secrets.TWINE_PASSWORD }}'
